apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mafia-helper-prod

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: web
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.jokermafia.am
      - op: replace
        path: /spec/rules/0/host
        value: app.jokermafia.am
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

generatorOptions:
  disableNameSuffixHash: true
