apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mafia-helper-dev

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: web
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.jokermafia.am
      - op: replace
        path: /spec/rules/0/host
        value: dev.jokermafia.am
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging

generatorOptions:
  disableNameSuffixHash: true
